= Angry Reader? Could this get better?
:hp-tags: ashleypark

**I sent her this today:**  
  
> Ashley,
> 
> I think you watch the news too much. First : The reason why we can’t find the airplane hijackers of 9-11 is because they went up in a cloud of smoke just like all our loved ones did. Second: ‘They’ aren’t smarter than us. We are just a lot bigger target. What is easier to catch? A pillow or the piece of lint falling from it? ‘They’ are mobile, and small. ‘They’ can slip in and out of the US without us knowing because it’s trying to find a needle in a haystack. Third: If you think ‘We’ are so dumb, and you’re the brainiac that has figured this out, why don’t you go and move to Canada. Fourth: “Master Mind”? I think someone has been watching too many movies. Fifth: If it is, as you believe that the terrorist as smarter than we are, I guarantee that my site, in no way, is going to effect what they think, because they would check on it. Sixth: How was the channel changed when they were calling for Mayday? This is the part were I understand that you are ignorant. A ‘Mayday’ is blasted over all standard channels. Hm, why would they do this? Oh, maybe because they don’t want the pilot to have to worry what channel he and whoever he is trying to contact are on the same channel when he plane is going down. Seventh: We haven’t sent an atomic bomb over to Iraq because that would start nuclear war, which results in everyone dieing... Which is bad. Eighth and final: If you have a better way to as you say ‘tighten up’ our security why don’t you say something? I mean if you are smarter than the whole country on exactly what we should be doing for homeland security, why are you being selfish and holding that knowledge to yourself? You could be saving countless American lives. Yeah, and death tolls.. not even going to touch that one, because if you had any patriotism at all you would have respect for them, and shut up.  
> 
> As always, the pleasure is all mine.  
> j.d.mubix 
  
**waiting for a rely... I’ve gotta make a seperate web site for this...**
