= Back to the Basics
:hp-tags: rant, gaming

Age of Empires II - Age of Kings. That is a great game. It has something that not a lot of games have these days. Which is replay value. Once you beat a game, that is it. No more fun. You know all the secrets.

That is where MMORPG came into the picture. But still most of them are still lacking. You can get to Level 60 or Level 70 and you have reached the top. You get stuck. So how does one make the prefect game? Easy make it last forever. Now you want to know how you do that? Aren't you selfish! Do I have to tell you everything?

Well since you aren't going to answer me I'll just assume that you mean yes. Well you make a game last forever by making it a game that you play with your buddies, with your friends. Make it a social event basically. Now I don't expect a game to start dispensing beer (although that would be a great feat). But make it something that rivals going out to... say the mall when you are bored, or even a movie theatre.

Now, you have to make it enjoyable. Make computer rivals so you can co-op with your buddy. Make more levels of difficulty than Easy, Medium, and Hard (and Legendary). Call MIT and ask for a AI with some ooomph. Put cheats in the game. For some people, cheating makes the game MORE enjoyable. For others it does not. But at least give them the option to do it. Well, except in multiplayer mode. hmm more later...
