= Internet Relay Abuse
:hp-tags: internet

A while ago, I posted a PHP Relay location to my site, and to a Hak5.org's forums. Recently I saw quite a bit of traffic going directly to that URL. I have taken action to ensure that this privledge that I am extending to the world, free of charge, is not abused. I have a cron job running that assess that use of that specific file and by what IPs. It then takes any IP with use over a certain limit and adds them to a complete block, to the relay, to my site, and any other site that I host. I am providing this service free of charge. Don't abuse it. As of now, the following IP addresses have been banned.  

```
195.229.242.53  
199.185.84.162  
213.42.2.0/24  
```
  
If you are in this range, or one of those IPs, then please email me, make amends, and I will unblock you. The reason I know you can get to this site, is you were using my relay, you will probably be able to find another.  
  
Thanks to all those who use in moderation and don't flood my servers,  
  
jd.mubix
