= An Interesting Flight
:hp-tags: rant, travel

Well, I am home. Not actually, I'm in the U.s. waiting for my flight to NOVA. I have a very interesting flight, more so than usual. First things first: No, the person next to me wasn't an old lady that wanted to talk my ear off or a crying baby. It was actually a mother of an adorable boy that was sitting near the window. But you don't want to hear about good stuff. That isn't interesting, you want to hear about the oddities, the bad stuff, and Inquirer type news. Well Inquirer, eat your heart out:  
  
Nazi Stewerdess: Before take off, this woman came out of no where, romped up the isle stopped at a very specific point, looked at the person sitting in seat '22 B' and said "FASTEN YOUR SEAT BELT". Then proceeded to romp off. Now I don't know if planes have the technology yet to do this or this woman just had little tiny video cameras installed in every seat, but she was scary. The thing that made this woman even more weird was the fact that she did this to a couple other times, yet, after take off, she was no where to be seen. She wasn't serving food, she wasn't colleting trash. My row mate and myself swore that she was now sitting in first class and all the other flight attendants were secretly saying 'Zig Hail' or however that phrase is spelled.  
  
The Beast: I saw this one a mile away. She was in the chair in front of mine, with here neck pillow, buckled in, persperating, while people were still boarding. She had two seats open next to her and she was trying to go to sleep. Then, when someone finally came to sit down, she shuffled them in and 'helped' slam their bags into the overhead bins. If that wasn't bad, she never put her seat upright, so when it came time to let my row mates in, they got the pleasure of squeezing by her lowered seat in an already cramped area. But the best part is yet to come. I opened up my laptop to watch episode 11 of [purepwnage](http://www.purepwnage.com/) and catch up on a little [Security Now](http://www.grc.com/sn), when she some how manages to put her seat even farther back. So here is me, at 6'4'' crammed into an Economy seat for 13 hours with no room as it is, and The Beast decides to recline her seat more. Yay. I was so afraid that she would manage the feat of putting her seat back farther and break my laptop's monitor that I turned it off and put it away. Now, don't get me wrong, I am usually a very nice person, and I initially felt pity for her because she looked quite scared to be on a plane, but it turned out to be annoyance, not fright. And, the name that I have given her does not denote weight, she is just mildly overweight. It is the combination of the ugly, the rudeness, the mild obecity, and the miraculous way she can bend a airline seat.  
  
I apologize for the long post. I just have nothing else better to do then wait for my next flight.  
  
mubix
