= Happy New Year
:hp-tags: rant

Yeah, I know it's been a while AGAIN since I have posted, but I just wanted to say Happy New Years to everyone. This year is going to be a very different one for me since my wife and I are expecting in Feb. I am really excited about my future son. It is a blessing to be able to bring a life into the world, and a big responsibility. I am also starting college back up. I will be going for a BS in Information Assurance.  Another thing that I want to point out is that I shovled out some dough and am getting 2 x 1 GB (Cas 2) 184pin DDR ram sticks. I am note sure what Cas 2 is, but I am told it's the best out right now. In other news, I went down to the party with the Hak.5 crew again and had a blast. I am starting to become a regular down there, which is fine by me. It is pretty refreshing to be able to have fun, party, and then sit down for a late night hack session all with the same people. In Bigger new (however not as big as my future son) I am now doing a podcast called Sploitcast with Harrison Holland and Jonny G' from Hak.5. Our first episode airs Jan 8 and I am extremely excited to see how it all turns out. Well. it is getting really late and it is way my bed time.
