= Hak.5 2x10 - USB Goodies with Encryption
:hp-tags: Uncategorized

Ok, so I got a lot of questions of how everything works on my encrypted U3 drive. I started off with the  
  
Here is what goes in my go.cmd file from the SwitchBlade  


> @echo off  
truecrypt /q /v saved.pst /lo  
o:pstart.exe

  
So what I am doing here is connecting the saved.pst file as a truecrypt volume using /v. I am using the /q so that it doesn’t open the whole Truecrypt GUI. The /lo tells truecrypt to mount it as the drive letter O:. It will prompt you for your password, it will mount, and then it will run pstart.exe from your mounted O: drive.  
  
**Where to get what I went over in the episode:**  
Truecrypt: [http://www.truecrypt.org/](http://www.truecrypt.org/)  
Software Information for Windows: [http://www.gtopala.com/](http://www.gtopala.com/)  
Baregrep: [http://www.baremetalsoft.com/baregrep/  
](http://www.baremetalsoft.com/baregrep/)  
  
I posed this question to the forums, but I wanted to ask here as well. My USB stick is about 3 gigs worth of tools. Would ya’ll be interested in a torrent with all of those tools in it? Leave your comments.  
  
mubix
