= Multicast and some random thoughts
:hp-tags: Rant, Rant

So I am a complete noob when it comes to multicast and recently I have been hearing about it more and more. I know it's been out there since the dawn of time but I simply thought it was a way of broadcasting video across the network. WRONG. So for those who don't know, and correct me if I am wrong, a computer or device sends out a multicast packet headed for a 244.X.X.X and just like a broadcast packet (255.255.255.255) it gets heard by everyone. Also like a broadcast packet, it falls within the broadcast boundary.  
  
So, why bring this up? Because I was thinking that a Multicast scanner would be a great tool for pentesters to use inside of a network to get a more complete picture of internal services.  
  
Also, as per the torrent. I have started assembling and organizing it. This way each item will be in an archive that you can choose to download or not from the torrent. Family is still in town so bare with me just a bit longer.
