= Podcasters Meetup
:hp-tags: Uncategorized

<p>So, last <a href="http://www.shmoocon.org/">Shmoocon (2007)</a> was my second year running at the con and we did something that hasn't been done before: A Security/Hacker's Pod/Vidcast meetup at the conference which gave a chance for their listeners/viewers to meet the people behind the mic/camera.  Well, a little less than one year later and plans for the next meetup are already underway. And, as I learn the ropes of putting something like this together we will be getting better venues and hopefully down the road meetups will pop up at <a href="http://www.defcon.org">Defcon</a> and other conferences.  Here are the details so far:</p>  
<ul>  
   <li>We will have hosts from: <a href="http://www.hak5.org/">Hak.5</a>, <a href="http://www.sploitcast.com/">SploitCast</a>, <a href="http://www.pauldotcom.com">PaulDotCom</a>, <a href="http://www.secthis.com/">Secthis</a>, and others that are getting back to me</li>  
   <li>At the moment we don't have a venue, but I am working on getting space inside the hotel</li>  
   <li>Free Beer and Free Food will be available until the tap runs dry. This depends on the venue, because some places in the hotel are not allowed to have liquor in them.</li>  
   <li>Also in the air is a live broadcast from ShmooCon</li>  
</ul>  
<h4><a href="http://www.podcastersmeetup.com"><span style="font-size: large;"><b>PODCASTERSMEETUP.COM</b></span></a></h4>  
<p>This is where future updates of meetups can be found. Also, if you want to run a meetup, if you are a podcaster and want to advertise your presence at a meetup, or you simply want to post news about the meetup or conference you can sign up for an account and send me an email telling me what you want to do and I'll get that hooked up for you.</p>  
<p>If you would like more information about the meetup, or you want to sponsor it please feel free to email me.   Thanks, mubix</p>
