= KVM MITM
:hp-tags: Rant, Rant

I’ve had an idea and I have been hashing it out the last couple days. I want a smal piece of hardware that runs basically a MITM, but a physical one. Something like those old keyloggers that you plug between a PS/2 keyboard and a computer. If it already exsists, please link me, but this is what I want it to do:  
  
Features of the KVM-MITM:  


  
	
  * **Ports**:  (2) DVI or VGA; (2) Ethernet NICs; (4) USB or/and (4) PS/2 Ports  <-- Half male, Half female
  
	
  * **Services**:  
  
	
    * VNC or RDP - a remote way to alter what is happening
  
	
    * Keylogger - recording all keys pushed through USB or PS/2 Mouse
  
	
    * SSH / SFTP - for reconfiguration or grabbing Keylogger data
  
	
    * IP snagger - management of using a static IP address within the DHCP scope automagically, without registering with DHCP
  
	
    * SSH Client for Tunneling local services
  
	
    * SSL Tunneling client for alternate means of tunneling if port 22 is blocked
  
	
    * Iptables - keep from a scan detecting the bridged nic (0 ports open, just tunnels outboud listening)
  
  

  
	
  * **Power Supply**: USB powered or a Male/Female plug for a standard desktop power cord
  
  
Just an idea.... any takers?
