= The Academy is giving away money!
:hp-tags: internet, hfc, theacademy

Ok, it's not to you, but it is to a good cause. Here is their blurb:

[Hackers for Charity](http://www.hackersforcharity.org/) helps non-malicious hackers gain valuable job experience by putting them to work on projects for charity. They also build computer classrooms to help children and adults break the cycle of poverty through empowerment training, and feed children with funds raised by sales of [Johnny Long's books](http://www.amazon.com/exec/obidos/search-handle-url/ref=ntt_athr_dp_sr_1?_encoding=UTF8&search-type=ss&index=books&field-author=Johnny%20Long).  
  
This month, I thought that it would be fun to partner up with [Hackers for Charity](http://www.hackersforcharity.org/) in order to raise money for the people of Uganda. [The Academy](http://www.theacademy.ca) has offered to donate $1 to [Hackers for Charity](http://www.hackersforcharity.org/) for every user that registers for a free account at [www.theacademy.ca](http://www.theacademy.ca) for the entire month of November. If you're a registered user already please forward this email or post it on a blog. Anything you can do to spread the word would be greatly appreciated. Let's try to make a substantial donation to charity this month. Thanks everybody!

So head on over and sign up. It's free and you can feel better about yourself. Plus you can help me in my goal to make The Academy's Director broke.
