= Microsoft making secret power plays?
:hp-tags: Rant, Rant

Recently I have been hearing a lot of innovators posting to their blogs that they are pursuing new employment with Microsoft, and I wonder if they are making sneaky power plays into the Open Source market. Taking it’s best projects and plucking their leads. For example:  
  
KnoppMyth Creator:  
  
[http://mysettopbox.tv/index.html#News](http://mysettopbox.tv/index.html#News)  
  
**EDIT**: The above article seems to be an April Fools joke that I was late to the party on. Thanks to Mark for calling me out.  
  
Castle Cops - Owner/Operator - Paul Laudanski  
  
[http://www.castlecops.com/t223152-Must_Read_Important_Announcement.html](http://www.castlecops.com/t223152-Must_Read_Important_Announcement.html)  
  
Now, don’t get me wrong, everyone needs their family and Open Source is a thankless job sometimes. I am not trying to dog on them for going Microsoft. I am just wondering if they are doing this to give these gents a job and make their product better, or just get rid of supporting competition.  
  
Just my rant on what I am seeing. Sounds a bit like dvorak.org/blog eh?  
  
-- mubix
