= Ear Trumpet
:hp-tags: robin wood, tools, egress

I have had the idea for this app for a long time, expressed it a few times, but never really pushed, and I sure that I am not the only one who has thought of or wanted an app like [Ear Trumpet](http://www.digininja.org/ear_trumpet.php) by [Robin Wood](http://www.digininja.org/). Well on Jan 21st Sam Buhlig posted to the [PaulDotCom mailing list ](http://mail.pauldotcom.com/cgi-bin/mailman/listinfo/pauldotcom) asking for an app to test a firewall that would answer on all ports. A great discussion spawned off and a couple guys (Dimitrios Kapsalis, and Robin Wood) started work on it.  
  
So what is Ear Trumpet? It’s a server/client app just like Cain and Abel is. But each piece has one very simple task: ear listens on a server on all TCP port, and trumpet tries to get to it on all TCP ports. That’s it.  
  
What does that do for me? Well, here are two instances where it could be useful:  

  * As a Firewall / Perimeter Technician, where you use it to test to see if all of your firewall rules are working properly so that no one can get through. (Outside in. Ear internal, Trumpet external)
  	
  * As a Penetration Tester, where you use it to find exfiltration points, ways out of the network. (Inside out, Ear external, Trumpet internal), You could even put Trumpet on multiple computers in this instance and see which systems have different access out. There are sleep methods plugged into Trumpet to allow you to stay under the radar.
  
What can you use it for? Simple programs like this always have a million uses. Comment with your idea.
