= Lies
:hp-tags: rant

When I was in middle school, I told a lie. I was so good at telling lies, and remembering even the infinite details of these lies that I could make them believable. Later in life, I learned that this skill was called “Social Engineering ;-)”, but back to the story; I told everyone that I had won a shopping spree at “Incredible Universe”, now named “Fry’s”. Even the teacher believed me. The kids made lists of what they wanted me to get for them, and I strung it on for way too long. You tell a lie like that though and you get caught eventually. As I did, and learned a hard lesson. At that time in my life I was going through some really rough waters, and having everyone “like” me for even that finite amount of time, helped me cope. Does that make it right? Definitely not. But I remember that experience to this day.

Why tell you all this? Because this post is both self serving (as it will make it impossible for me to lie about the following any more) and apologetic. I have lied to those I call friend. Recently these lies were told to some very good friends and I had my first physical reaction to the guilt of telling them. I was literally unable to eat that night. Enough stalling and making excuses here they are:
  
  1. I am not a Marine Scout Sniper, nor ever been to Marine Scout Sniper school. I truly wish I had been and admire all those who have made it through.
   
  2. I have never been to SEARS training.
   
  3. The gentleman by the name of Fuzzy, was a gas attendant with me. Great guy, but he wasn’t an explosives expert in Okinawa to the best of my knowledge.
   
  4. Never met the Rock Marines of Korea, or for that matter trained with any other foreign military.
   
  5. I have never been to a Masseuse school, but I give great massages, ask anyone.
   
  6. I was never a bouncer in NY or lived there. Only been there twice on vacation, but love the city, and the Yankees (although I have no idea who plays for or owns the team) nor do I follow them, or for that matter any sports team.
   
  7. I have been a bartender, but it was for a base beach snack bar that I followed mix solutions on a printed paper for, so I know absolutely nothing about mixed drinks.
 
I have never told these lies during an interview or any other formal means, but I have told them to friends and acquaintances. I would like to apologize to all of them, here and now. I originally thought I should email them, but decided this public forum was a better and a bit more transparent.

Are the lies damaging to anyone but me? Did I have to tell anyone? No, not really. Would someone figure out that they were lies? There is a small chance. But that’s not the point. I try to be as brutally honest as I can with people, and I want that to extend to things about myself.

Think of me what you will, and I am deeply sorry if I misrepresented myself to you in any fashion at any time.

Rob
