= My iPhone runs Windows
:hp-tags: iphone, rant

(This is the 3rd time I am writing this post, FF Fail, then Word crashed, so please excuse the lack of passion)  
  
The moment that PDANet published that they released an updated version that allows USB tethering, I ran home and “QuickPWNd” my phone (which took all 5 minutes). Loaded the app and now I had the coveted TETHERING. I was free of my bind to Comcast or Free Public Wifi. However, over the next few months, my iPhone started getting slower and slower to respond. Crashes happened on apps that never had a problem before (including Safari). It would even crash on incoming calls.  
  
5 minutes ago (now more like 20), I had it crash again and slow responsiveness down to unbearable speeds. (2 minutes from touch to fully started app). When I had an internal debate: Would I go home and de-PWN it, or deal with it? With that same thought I realized that at the core of most of the technologies we use today, Windows, Twitter, MySpace (now Facebook), is an underlying need, freedom, or other feature that they provide that makes them ‘bearable’.  
  
Twitter’s FAIL WHALE is famous because Twitter crashes or is down A LOT. Why do you still use it? Windows is an utter mess of code and BSOD even had a hardware device made for it. Why do you still use it? ...you get the point.  
  
I’m not going to revert my iPhone back. You know why? Because the freedom that it provides me, (like typing a blog post for the 3rd time going 65 miles an hour in the back seat of a car) is worth it, to me.
