= 'Kindle 2 Review: Putting The Fire Out'
:hp-tags: review, kindle

Now, before you get all huffy about the title, it's not what you think. Keep reading:  
  
It's been 20 days since I received my Kindle 2 (word of warning, NEVER use USPS. Spend the money; it's not worth the stress). But enough of lullygaging, let me get straight to it:  


## Advertised Features:

  * **Email DOC, HTML/HTM, JPEG/JPG, GIF, PNG, BMP (Also, everything can be put in a ZIP for one time sending).**  
	
    * All of these worked well, I very surprised that DOCX worked so well, and they actually prefer it (since it's based on XML it comes out cleaner after the conversion). However when you start getting into the images, it can get a bit harry when going to higher resolutions. My Kindle locked up on a 3 MB hi-res PNG of my boys (remember this is after Amazon converted it).

  * **Email PDF**  

    * As they say, this is experimental. There are desktop software converters (not specifically designed for the Kindle) that do a much better job (and are free). But we'll talk more about that in the 'hacks' portion (Amazon charges 10 cents per PDF)
  
  * **Text to Speech**  
 
    * Granted I haven't used much other T2S programs in my day other than Microsoft ?Steve?. This is a feature that I find phenomenal. I am one of those types who sometimes can't quite concentrate on the reading of a book, and when I get to that point I switch on the T2S and can keep enjoying the book. The only annoying part, but understandable, is in picture quotes or code snippets, it reads through them the best it can, which is sometimes painful.
	
  * **Fast Page Turns, Longer Battery Life, Improved Display, More Storage**  
  
    * I can't really attest to them being better or worse than the Kindle 1, but:  
	
      * It turns pages REALLY slow, and REALLY fast some times, kinda depends on it's mood, time of the month, or position of the moon, not sure, but it isn't due to the amount of content on the next page, amount of rapid fire page turns, or battery life. I can't quite figure out the rhyme or reason.
	
      * The battery life is phenomenal, I charge it once a week, possibly more if I'm reading a ton. I believe this is due to me turning off the 3G. You don't need it on if you aren't sending a doc or shopping for a book.  
	
      * The 'electronic paper' reacts to light just as real piece of paper would. Looks better in high light conditions, and only has a glare if you're pointing a light directly at it.
	
      * This is where I got a bit miffed. The Kindle 1 had a SD card slot, the Kindle 2 had just 2 GB of flash storage. However, after putting umpteen PDFs, Docs, and even a couple audio books (Audible format and MP3). I still haven't used up the space.

  * **Large Selection, Low Book Prices**  
  
    * Their selection of technical books is quite lacking. And their prices are only a few dollars off something that you aren't getting physically, something you can't lend a friend or flip through. I agree with a bunch of the press that is going around hammering Amazon for their "9.99" advertising. But, there is a light at the end of the tunnel. Plenty of technical book publishers offer eBooks versions on their site (O'Reilly to name one) and their formats are Kindle friendly. You can find most of the books that you want, you just have to do a bit more digging than flipping through the Kindle Store
	
  * **Kindle Store (Blogs, Newpapers, Magazines)**  
  	
    * Alright, paying to read a blog is just plain bull. I don't care if they deliver it in a pretty format. Newspapers I don't feel much better about, but Magazines I can kind of understand. But I still run into the brick wall of why they are charging so much for something that you can't share.
  
  * **3G Wireless**  
  
	
    * The power of the antenna on the Kindle is horrible. So much that I want to buy one of those "Seen On TV" cellular antenna boosting stickers. I understand the power struggle, battery life over connectivity, I get it. But let come on! Why do I go out of single if I set it down? But, back to an earlier point, I only have it on when I want to look for a book in the store or email one to my Kindle. It certainly isn't a deal breaker for me.
  
  * **Browser**  
	
    * No,.. just no. If this was 1995 and there was no dynamic content on pages this browser would have fit perfectly. If you must use this feature, look for the mobile sites, use those. Again, not a deal breaker, I have an iPhone that does browsing if needed, I don't need my "book" to browse... yet.

  * **Just plain gripes**  
	
    * USB Ultra Thin is almost as hard to come by as the iPod/iPhone interface, if not harder. Why not use mini USB like everyone else on the planet? I hate forgetting chargers on trips and having to go and buy one. 
  
    * No scroll wheel. I think this is something that is not only missing on the Kindle but the iPhone as well. Blackberry got famous on that wheel and they are screwing it up with that stupid ball.
	
    * Lastly, it's not very right hand friendly. I'm a lefty but sometimes it's just more convenient to hold it with my right hand, and there is no page back on the right. So to flip back a page it more muscles that I have to use, and I'm lazy ;-)
  
## "Hacks"

  1. Converting PDFs the right and WRONG way: Do not waste your time with Stanza. Their iPhone eBook reader app is awesome, but the converter for PDFs is downright horrid. Use a program called MobiPocket Creator. Be sure to install the Publisher version when it asks during the install. It's a convoluted process, but your end result is SO much better than both the Stanza way, and Amazon's own converter. Follow the 6 steps: [HERE](http://ireaderreview.com/2008/01/18/how-to-view-pdf-files-on-the-kindle/). And you'll be fine. Yes, it's a Windows program. I haven't researched Mac programs, and the Linux ones where just two complicated to be useful.

  2. If you MUST use the browser, turn on Advanced Mode and Javascript.  The Kindle has compartmentalized it's Settings, so go into the Experimental -> Browser and then Menu-> Settings. 

  3. Use your pads. If you are used to typing, you use the tips of your fingers. Typing on the Kindle works SO much better if you use the pads of your fingers.   
	
  4. Want to save a bit of code for later? Highlight it. It will go into your "My Clippings" in and you'll not only be able to access it and see the whole clipping, but you'll be able to go directly to that line (Kindle doesn't use pages) in the book, and be able to read back up if needed. Even if that book is way back in your history.
	
  5. Cheat Sheets. I created my own cheat sheets in Word, converted some of the ones Ed Skoudis made and a munch of others, now I have them on my Kindle and have access to them at a moments notice. Those familiar with ClickScripts will really enjoy this aspect of the Kindle. Wrap your head around that it's not just for books, and you'll start seeing a whole new world of things you can put on your Kindle.
 
## What would put the Kindle on FIRE

  * Just one request, but it would hands down make the Kindle worth every cent of the 350 price tag. I want Amazon to take the contents of an email, if no other attachments exist, and send it to me as text or HTML on my Kindle. This helps me two fold. First, if I have a lengthy email that I want to read later, I can do so without straining on my iPhone to read it. Second, I can use Google Reader's email article function to turn the Kindle into an off-site Google Reader.
  
## Conclusion

Yes, I do think I made a great choice in my selection over a Netbook. With any technology, especially one that pushes the industry, there will be positives and negatives. But, I am reading more, and thoroughly enjoying a small sneak preview of [F0rb1dd3n](http://f0rb1dd3n.com/) by my good friend Jayson Street. Bottom line, it's a solid buy. I would highly suggest it for anyone on the go, people who never can find the time to read, and people who don't like carrying a library with them everywhere.
