= 'APPLE: A Modern Day Willy Wonka Story'
:hp-tags: internet, rant

Yes, I just called everyone who works at Apple an Oompa Loompa, but I digress:

I was reading Brooke Crothers' story on the Apple 'gag' order [1] and couldn't help but think of how Apple has created an almost similar situation. Everyone wants to know what Apple is up to, can't stop talking about it. Buzz Out Loud [2] even had people call and email asking them to see if they could do a show without mentioning Apple or the iPhone. According to Brooke's article, people are afraid for their very jobs (pun?) even in the mentioning of Apple. What's behind the curtains at Apple? Is Steve Jobs going to send out 5 golden Apple Tablets? Probably not, but I can't shake the image of Steve coming out on stage to do one of his presentations with a cane and doing a fake fall to the podium.

So I pose this crucial question to you, the reader: Who plays the part of Slugworth?

[1] [http://news.cnet.com/8301-13924_3-10372535-64.html?part=rss&subj=news&tag=2547-1_3-0-20](http://news.cnet.com/8301-13924_3-10372535-64.html?part=rss&subj=news&tag=2547-1_3-0-20)

[2] [http://bol.cnet.com](http://bol.cnet.com)
