= Free Ticket Contest - Metasploit Mastery at DerbyCon
:hp-tags: derbycon, training, cons

Egypt and I have decided to give away a spot in our training event at DerbyCon. This won’t come easy though, you have to submit an essay to us with one of the following topics:  
  
Essay Topic Options:  
1. Why I deserve a free training class  
2. How I would social engineer Egypt and Mubix out of a ticket to their class  
  
Maximum Length: ~1000 words / 3 pages. (We're lazy)  
Submissions sent in direct email, PDF, or Doc(x) (extra points for zero day!) format to: [derbyessay@room362.com](mailto:derbyessay@room362.com)  
  
The due date for a valid submission is 2359 GMT on August 15th, decisions will be made that weekend (August 18th & 19th) and the winner will be announced (and emailed direction how to obtain class info) on the 20th. **

**Good luck!**

**-- egypt and mubix**

Also check out corelanc0der's contest for a spot in his class here: [https://www.corelan.be/index.php/2012/08/05/corelan-t-shirt-contest-derbycon-2012/](https://www.corelan.be/index.php/2012/08/05/corelan-t-shirt-contest-derbycon-2012/)

P.S. Dont' know what DerbyCon is or the training we are providing? Here are some #lazyweb links:

Derbycon: [https://www.derbycon.com/](https://www.derbycon.com/)

Our training at Derbycon: [https://www.derbycon.com/training-courses/#metasploit](https://www.derbycon.com/training-courses/#metasploit)

Outline of the training (it's changed a bit but generally right): [/blog/2012/05/22/derbycon-training-sep-27-28-2012/](/blog/2012/05/22/derbycon-training-sep-27-28-2012/)
